import type { ModelIR } from '../ir'
import type { Change, MigrationContext } from './types'

/**
 * What every migration script opens with: where it came from, which revisions it
 * connects, and the change set it realizes, so a reviewer reads the intent beside the
 * statements. `c` is the target's comment marker. See lat.md/emitters#Migrations.
 */
export function migrationHeader(
  c: string, target: string, after: ModelIR, changes: Change[], context: MigrationContext, notes: string[],
): string[] {
  const width = Math.max(...changes.map((x) => x.class.length))
  return [
    `${c} Generated by lpg-modeler. Target: ${target} migration.`,
    `${c} Model: ${after.namespace.prefix} <${after.namespace.iri}>`,
    `${c} Revision ${context.fromRevision} -> ${context.toRevision}.`,
    c,
    ...notes.map((n) => (n ? `${c} ${n}` : c)),
    ...(notes.length > 0 ? [c] : []),
    `${c} Changes since revision ${context.fromRevision}:`,
    ...changes.map((x) => `${c}   ${x.class.padEnd(width)}  ${x.label}: ${x.detail}`),
    '',
  ]
}

/** The line a script carries instead of statements when nothing it stores changed. */
export const noSchemaEffect = (c: string, target: string): string =>
  `${c} No schema effect on ${target}: nothing this target stores differs between the two revisions.`

/** The comment every destructive statement is preceded by. */
export const destructiveNote = (c: string, element: string, why: string): string =>
  `${c} DESTRUCTIVE: ${element}: ${why}`
