// Generated by lpg-modeler. Target: memgraph.
// Model: comp <https://example.org/vocab/comp#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

// Sensor
CREATE CONSTRAINT ON (n:Sensor) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Sensor) ASSERT EXISTS (n.id);
CREATE INDEX ON :Sensor(id);
CREATE CONSTRAINT ON (n:Sensor) ASSERT n.id IS TYPED STRING;
// UNENFORCED: 'embedding' is float[128] in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'rgb' is uint8[3] in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'location' is STRUCT(lat float, lon float, label string) in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'tags' is MAP(string, string) in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'reading' is UNION(num float, text string) in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'history' is STRUCT(at datetime, values float[])[] in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.
// UNENFORCED: 'grid' is int[][] in the model; Memgraph can only
// say a value is some map or list, so no type constraint is emitted.

// (:Sensor)-[:CALIBRATED_BY]->(:Sensor)
// UNENFORCED: 'offsets' is MAP(string, decimal(10,2)) in the model.
