// Generated by lpg-modeler. Target: memgraph.
// Model: fleet <https://example.org/vocab/fleet#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

CREATE ENUM Status VALUES { active, retired };

// Driver
CREATE CONSTRAINT ON (n:Driver) ASSERT n.licence IS UNIQUE;
CREATE CONSTRAINT ON (n:Driver) ASSERT EXISTS (n.licence);
CREATE INDEX ON :Driver(licence);
CREATE CONSTRAINT ON (n:Driver) ASSERT n.licence IS TYPED STRING;
// PARTIAL: 'nicknames' must be a list; its elements being string is unenforced.
CREATE CONSTRAINT ON (n:Driver) ASSERT n.nicknames IS TYPED LIST;
// PARTIAL: 'status' must be an enum value; that it is a Status value is unenforced.
CREATE CONSTRAINT ON (n:Driver) ASSERT n.status IS TYPED ENUM;

// Vehicle
CREATE CONSTRAINT ON (n:Vehicle) ASSERT n.vin IS UNIQUE;
CREATE CONSTRAINT ON (n:Vehicle) ASSERT EXISTS (n.vin);
CREATE INDEX ON :Vehicle(vin);
CREATE CONSTRAINT ON (n:Vehicle) ASSERT n.vin IS TYPED STRING;
// PARTIAL: 'tags' must be a list; its elements being string is unenforced.
CREATE CONSTRAINT ON (n:Vehicle) ASSERT n.tags IS TYPED LIST;

// (:Driver)-[:DRIVES]->(:Vehicle)
// UNENFORCED: many-to-one in the model; Memgraph has no multiplicity constraint.
