// Generated by lpg-modeler. Target: neo4j.
// Model: social <https://example.org/vocab/social#>
// Edition: enterprise
//
// Neo4j has no table DDL. A hierarchy is expressed as labels, so a Person node
// also carries every ancestor label. See lat.md/emitters#Neo4j Target.

CREATE CONSTRAINT car_key IF NOT EXISTS
  FOR (n:Car) REQUIRE (n.vin) IS NODE KEY;

// Company carries labels :Company :Party (hierarchy flattened to labels).
CREATE CONSTRAINT company_key IF NOT EXISTS
  FOR (n:Company) REQUIRE (n.id) IS NODE KEY;

// Person carries labels :Person :Party (hierarchy flattened to labels).
CREATE CONSTRAINT person_key IF NOT EXISTS
  FOR (n:Person) REQUIRE (n.id) IS NODE KEY;
CREATE CONSTRAINT person_email_unique IF NOT EXISTS
  FOR (n:Person) REQUIRE n.email IS UNIQUE;
CREATE CONSTRAINT person_email_exists IF NOT EXISTS
  FOR (n:Person) REQUIRE n.email IS NOT NULL;
CREATE CONSTRAINT person_created_at_exists IF NOT EXISTS
  FOR (n:Person) REQUIRE n.createdAt IS NOT NULL;
CREATE INDEX person_created_at IF NOT EXISTS
  FOR (n:Person) ON (n.createdAt);

// (:Person)-[:KNOWS]->(:Person)

// (:Person)-[:LIKES]->(:Company)

// (:Party)-[:OWNS]->(:Car)
