// Generated by lpg-modeler. Target: memgraph audit.
// Model: social <https://example.org/vocab/social#>
//
// One read-only query per constraint memgraph leaves unenforced; each returns a
// 'violations' count, and zero everywhere means the data honours the model.

// [closed] Car closed
MATCH (n:Car) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vin', 'seats'] RETURN count(DISTINCT n) AS violations;

// [closed] Company closed
MATCH (n:Company) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vat', 'id'] RETURN count(DISTINCT n) AS violations;

// [closed] Person closed
MATCH (n:Person) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['email', 'born', 'createdAt', 'id'] RETURN count(DISTINCT n) AS violations;
