-- Generated by lpg-modeler. Target: sqlpgq (DuckDB with the duckpgq extension).
-- Model: social <https://example.org/vocab/social#>
--
-- Tables carry the constraints; the property graph at the end maps them. Abstract node
-- types are flattened to one table per concrete type, with inherited columns copied down.
-- Run with: INSTALL duckpgq FROM community; LOAD duckpgq; then this script.
-- See lat.md/emitters#SQL/PGQ Target.

-- Abstract, no table emitted: Party

CREATE TABLE IF NOT EXISTS Car (
  vin VARCHAR NOT NULL,
  seats BIGINT,
  PRIMARY KEY (vin)
);

CREATE TABLE IF NOT EXISTS Company (
  vat VARCHAR,
  id VARCHAR NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Person (
  email VARCHAR NOT NULL UNIQUE,
  born DATE,
  createdAt TIMESTAMP NOT NULL,
  id VARCHAR NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS KNOWS (
  src_id VARCHAR NOT NULL,
  dst_id VARCHAR NOT NULL,
  since DATE,
  FOREIGN KEY (src_id) REFERENCES Person (id),
  FOREIGN KEY (dst_id) REFERENCES Person (id)
);

CREATE TABLE IF NOT EXISTS LIKES (
  src_id VARCHAR NOT NULL,
  dst_id VARCHAR NOT NULL,
  FOREIGN KEY (src_id) REFERENCES Person (id),
  FOREIGN KEY (dst_id) REFERENCES Company (id)
);

-- 'Party' and/or 'Car' are abstract; this is the Company → Car pair.
CREATE TABLE IF NOT EXISTS OWNS_Company_Car (
  src_id VARCHAR NOT NULL,
  dst_vin VARCHAR NOT NULL,
  since DATE,
  FOREIGN KEY (src_id) REFERENCES Company (id),
  FOREIGN KEY (dst_vin) REFERENCES Car (vin)
);

-- 'Party' and/or 'Car' are abstract; this is the Person → Car pair.
CREATE TABLE IF NOT EXISTS OWNS_Person_Car (
  src_id VARCHAR NOT NULL,
  dst_vin VARCHAR NOT NULL,
  since DATE,
  FOREIGN KEY (src_id) REFERENCES Person (id),
  FOREIGN KEY (dst_vin) REFERENCES Car (vin)
);

CREATE OR REPLACE PROPERTY GRAPH social
  VERTEX TABLES (
    Car PROPERTIES (vin, seats) LABEL Car,
    Company PROPERTIES (vat, id) LABEL Company,
    Person PROPERTIES (email, born, createdAt, id) LABEL Person
  )
  EDGE TABLES (
    KNOWS SOURCE KEY (src_id) REFERENCES Person (id) DESTINATION KEY (dst_id) REFERENCES Person (id) PROPERTIES (since) LABEL KNOWS,
    LIKES SOURCE KEY (src_id) REFERENCES Person (id) DESTINATION KEY (dst_id) REFERENCES Company (id) NO PROPERTIES LABEL LIKES,
    OWNS_Company_Car SOURCE KEY (src_id) REFERENCES Company (id) DESTINATION KEY (dst_vin) REFERENCES Car (vin) PROPERTIES (since) LABEL OWNS_Company_Car,
    OWNS_Person_Car SOURCE KEY (src_id) REFERENCES Person (id) DESTINATION KEY (dst_vin) REFERENCES Car (vin) PROPERTIES (since) LABEL OWNS_Person_Car
  );
