// Generated by lpg-modeler. Target: typescript.
// Model: social <https://example.org/vocab/social#>
//
// Interfaces mirror the model: a parent and a mixin are both `extends`, and a type
// declares only its own properties. What a type system cannot enforce — keys,
// uniqueness, value bounds, cardinality — is JSDoc at the site and data in the
// SCHEMA const below. See lat.md/emitters#TypeScript Target.

/** A calendar date. Drivers disagree on the runtime shape; remap once here. */
export type LpgDate = string
/** A timestamp without an offset. */
export type LpgDateTime = string
/** A timestamp with a time zone offset. */
export type LpgZonedDateTime = string
/** An exact decimal, kept as text so no precision is silently lost. */
export type LpgDecimal = string
/** An ISO 8601 duration. */
export type LpgDuration = string

export interface Timestamped {
  createdAt: LpgDateTime
}

export interface Car {
  /** key */
  vin: string
  seats?: number
}

export interface Company extends Party {
  vat?: string
}

/** Abstract: no instance carries exactly this type. */
export interface Party {
  /** key */
  id: string
}

export interface Person extends Party, Timestamped {
  /** unique */
  email: string
  born?: LpgDate
}

/** Edge KNOWS: Person → Person (many-to-many). */
export interface KNOWS {
  since?: LpgDate
}

/** Edge LIKES: Person → Company (many-to-many). */
export interface LIKES {
}

/** Edge OWNS: Party → Car (many-to-many). */
export interface OWNS {
  since?: LpgDate
}

/** Concrete node types, for lookup by label. */
export interface NodeTypes {
  Car: Car
  Company: Company
  Person: Person
}

/** Edge property shapes, by edge type name. */
export interface EdgeTypes {
  KNOWS: KNOWS
  LIKES: LIKES
  OWNS: OWNS
}

/** What the interfaces cannot carry: labels, keys, endpoints, cardinality. */
export const SCHEMA = {
  prefix: 'social',
  iri: 'https://example.org/vocab/social#',
  nodes: {
    Car: { labels: ['Car'], key: ['vin'], abstract: false },
    Company: { labels: ['Company', 'Party'], key: ['id'], abstract: false },
    Party: { labels: ['Party'], key: ['id'], abstract: true },
    Person: { labels: ['Person', 'Party'], key: ['id'], abstract: false },
  },
  edges: {
    KNOWS: { from: 'Person', to: 'Person', cardinality: 'many-to-many' },
    LIKES: { from: 'Person', to: 'Company', cardinality: 'many-to-many' },
    OWNS: { from: 'Party', to: 'Car', cardinality: 'many-to-many' },
  },
} as const
