#!/bin/sh
# Generated by lpg-modeler. Target: falkordb (FalkorDB).
# Model: social <https://example.org/vocab/social#>
#
# FalkorDB splits its schema across two protocols: an index is Cypher, a constraint
# is a Redis command. No single client applies both, so this is a shell script over
# redis-cli rather than a .cypher file -- which is also what lets it carry the
# downgrade notes below, since a line a redis pipe does not understand is an error.
#
#   sh <this file>            REDIS_CLI and GRAPH_KEY override the defaults below.
#
# Not idempotent. FalkorDB has no IF NOT EXISTS for an index or a constraint, so a
# second run reports each one as already existing and changes nothing.
#
# A constraint is applied asynchronously: the command returns PENDING and enforcement
# follows. If data already in the graph violates it, the constraint ends FAILED and is
# never enforced -- so run GRAPH.CONSTRAINT LIST afterwards rather than assuming.
#
# A hierarchy is expressed as labels, so a node carries its own label and every
# ancestor label too. FalkorDB is schema-optional, so a closed type is documentation
# here, not a constraint: a property may always appear that the type does not declare.

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-social}"

# Car
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Car) ON (n.vin)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Car PROPERTIES 1 vin
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Car PROPERTIES 1 vin

# Company carries labels :Company :Party (hierarchy flattened to labels).
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Company) ON (n.id)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Company PROPERTIES 1 id
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Company PROPERTIES 1 id

# Person carries labels :Person :Party (hierarchy flattened to labels).
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Person) ON (n.id)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Person PROPERTIES 1 id
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Person PROPERTIES 1 id
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Person) ON (n.email)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Person PROPERTIES 1 email
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Person PROPERTIES 1 email
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Person PROPERTIES 1 createdAt

# (:Person)-[:KNOWS]->(:Person)

# (:Person)-[:LIKES]->(:Company)

# (:Party)-[:OWNS]->(:Car)
