// Generated by lpg-modeler. Target: ladybug audit.
// Model: social <https://example.org/vocab/social#>
//
// One read-only query per constraint ladybug leaves unenforced; each returns a
// 'violations' count, and zero everywhere means the data honours the model.

// [required] Person.email required
MATCH (n:Person) WHERE n.email IS NULL RETURN count(*) AS violations;

// [unique] Person.email unique
MATCH (n:Person) WHERE n.email IS NOT NULL WITH n.email AS value, count(*) AS c WHERE c > 1 RETURN count(*) AS violations;

// [required] Person.createdAt required
MATCH (n:Person) WHERE n.createdAt IS NULL RETURN count(*) AS violations;
