// Generated by lpg-modeler. Target: neo4j audit.
// Model: social <https://example.org/vocab/social#>
//
// One read-only query per constraint neo4j leaves unenforced; each returns a
// 'violations' count, and zero everywhere means the data honours the model.

// [key-present] Car key part vin
MATCH (n:Car) WHERE n.vin IS NULL RETURN count(*) AS violations;

// [closed] Car closed
MATCH (n:Car) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vin', 'seats'] RETURN count(DISTINCT n) AS violations;

// [key-present] Company key part id
MATCH (n:Company) WHERE n.id IS NULL RETURN count(*) AS violations;

// [closed] Company closed
MATCH (n:Company) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vat', 'id'] RETURN count(DISTINCT n) AS violations;

// [key-present] Person key part id
MATCH (n:Person) WHERE n.id IS NULL RETURN count(*) AS violations;

// [required] Person.email required
MATCH (n:Person) WHERE n.email IS NULL RETURN count(*) AS violations;

// [required] Person.createdAt required
MATCH (n:Person) WHERE n.createdAt IS NULL RETURN count(*) AS violations;

// [closed] Person closed
MATCH (n:Person) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['email', 'born', 'createdAt', 'id'] RETURN count(DISTINCT n) AS violations;
