# Generated by lpg-modeler. Target: falkordb audit.
# Model: social <https://example.org/vocab/social#>
#
# One read-only query per constraint falkordb leaves unenforced; each returns a
# 'violations' count, and zero everywhere means the data honours the model.

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-social}"

# [closed] Car closed
$REDIS_CLI GRAPH.RO_QUERY "$GRAPH_KEY" "MATCH (n:Car) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vin', 'seats'] RETURN count(DISTINCT n) AS violations"

# [closed] Company closed
$REDIS_CLI GRAPH.RO_QUERY "$GRAPH_KEY" "MATCH (n:Company) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['vat', 'id'] RETURN count(DISTINCT n) AS violations"

# [closed] Person closed
$REDIS_CLI GRAPH.RO_QUERY "$GRAPH_KEY" "MATCH (n:Person) UNWIND keys(n) AS k WITH n, k WHERE NOT k IN ['email', 'born', 'createdAt', 'id'] RETURN count(DISTINCT n) AS violations"
