// Generated by lpg-modeler. Target: neo4j.
// Model: social <https://example.org/vocab/social#>
// Edition: community
//
// Neo4j has no table DDL. A hierarchy is expressed as labels, so a Person node
// also carries every ancestor label. See lat.md/emitters#Neo4j Target.

// DOWNGRADE: NODE KEY requires Enterprise. Uniqueness only; presence unenforced.
CREATE CONSTRAINT car_key_unique IF NOT EXISTS
  FOR (n:Car) REQUIRE (n.vin) IS UNIQUE;

// Company carries labels :Company :Party (hierarchy flattened to labels).
// DOWNGRADE: NODE KEY requires Enterprise. Uniqueness only; presence unenforced.
CREATE CONSTRAINT company_key_unique IF NOT EXISTS
  FOR (n:Company) REQUIRE (n.id) IS UNIQUE;

// Person carries labels :Person :Party (hierarchy flattened to labels).
// DOWNGRADE: NODE KEY requires Enterprise. Uniqueness only; presence unenforced.
CREATE CONSTRAINT person_key_unique IF NOT EXISTS
  FOR (n:Person) REQUIRE (n.id) IS UNIQUE;
CREATE CONSTRAINT person_email_unique IF NOT EXISTS
  FOR (n:Person) REQUIRE n.email IS UNIQUE;
// UNENFORCED: 'email' is required; existence constraints require Enterprise.
// UNENFORCED: 'createdAt' is required; existence constraints require Enterprise.
CREATE INDEX person_created_at IF NOT EXISTS
  FOR (n:Person) ON (n.createdAt);

// (:Person)-[:KNOWS]->(:Person)

// (:Person)-[:LIKES]->(:Company)

// (:Party)-[:OWNS]->(:Car)
