// Generated by lpg-modeler. Target: memgraph.
// Model: social <https://example.org/vocab/social#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

// Car
CREATE CONSTRAINT ON (n:Car) ASSERT n.vin IS UNIQUE;
CREATE CONSTRAINT ON (n:Car) ASSERT EXISTS (n.vin);
CREATE INDEX ON :Car(vin);
CREATE CONSTRAINT ON (n:Car) ASSERT n.vin IS TYPED STRING;
CREATE CONSTRAINT ON (n:Car) ASSERT n.seats IS TYPED INTEGER;

// Company carries labels :Company :Party.
CREATE CONSTRAINT ON (n:Company) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Company) ASSERT EXISTS (n.id);
CREATE INDEX ON :Company(id);
CREATE CONSTRAINT ON (n:Company) ASSERT n.vat IS TYPED STRING;
CREATE CONSTRAINT ON (n:Company) ASSERT n.id IS TYPED STRING;

// Person carries labels :Person :Party.
CREATE CONSTRAINT ON (n:Person) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT EXISTS (n.id);
CREATE INDEX ON :Person(id);
CREATE CONSTRAINT ON (n:Person) ASSERT n.email IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT EXISTS (n.email);
CREATE CONSTRAINT ON (n:Person) ASSERT n.email IS TYPED STRING;
CREATE CONSTRAINT ON (n:Person) ASSERT n.born IS TYPED DATE;
CREATE CONSTRAINT ON (n:Person) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Person) ASSERT n.createdAt IS TYPED LOCALDATETIME;
CREATE CONSTRAINT ON (n:Person) ASSERT n.id IS TYPED STRING;
CREATE INDEX ON :Person(createdAt);

// (:Person)-[:KNOWS]->(:Person)

// (:Person)-[:LIKES]->(:Company)

// (:Party)-[:OWNS]->(:Car)
