// Generated by lpg-modeler. Target: memgraph.
// Model: types <https://example.org/vocab/types#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

// Reading
CREATE CONSTRAINT ON (n:Reading) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Reading) ASSERT EXISTS (n.id);
CREATE INDEX ON :Reading(id);
CREATE CONSTRAINT ON (n:Reading) ASSERT n.id IS TYPED STRING;
// PARTIAL: 'tiny' is int8 in the model; the constraint does not hold its 8-bit width.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.tiny IS TYPED INTEGER;
// PARTIAL: 'small' is int16 in the model; the constraint does not hold its 16-bit width.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.small IS TYPED INTEGER;
// PARTIAL: 'medium' is int32 in the model; the constraint does not hold its 32-bit width.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.medium IS TYPED INTEGER;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.big IS TYPED INTEGER;
// PARTIAL: 'huge' is int128 in the model; the constraint does not hold its 128-bit range; a Memgraph integer is 64-bit.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.huge IS TYPED INTEGER;
// PARTIAL: 'utiny' is uint8 in the model; the constraint does not hold that it is unsigned and 8-bit.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.utiny IS TYPED INTEGER;
// PARTIAL: 'usmall' is uint16 in the model; the constraint does not hold that it is unsigned and 16-bit.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.usmall IS TYPED INTEGER;
// PARTIAL: 'umedium' is uint32 in the model; the constraint does not hold that it is unsigned and 32-bit.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.umedium IS TYPED INTEGER;
// PARTIAL: 'ubig' is uint64 in the model; the constraint does not hold that it is unsigned; a Memgraph integer is signed 64-bit.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.ubig IS TYPED INTEGER;
// PARTIAL: 'ratio' is float32 in the model; the constraint does not hold its 32-bit precision.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.ratio IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.precise IS TYPED FLOAT;
// PARTIAL: 'amount' is decimal in the model; the constraint does not hold its exact decimal precision.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.amount IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.ok IS TYPED BOOLEAN;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.day IS TYPED DATE;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.at IS TYPED LOCALDATETIME;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.atZoned IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Reading) ASSERT n.took IS TYPED DURATION;
// UNENFORCED: 'ref' is uuid in the model; the constraint does not hold any type at all: Memgraph has no UUID type, and STRING would admit any string.
// UNENFORCED: 'raw' is blob in the model; the constraint does not hold any type at all: Memgraph has no binary type.
// UNENFORCED: 'payload' is json in the model; the constraint does not hold any type at all: Memgraph has no JSON type.
// PARTIAL: 'samples' must be a list; its elements being decimal is unenforced.
CREATE CONSTRAINT ON (n:Reading) ASSERT n.samples IS TYPED LIST;
