import type {
  Assertion, ConstraintIR, EdgeTypeIR, ModelIR, NodeTypeIR, PropertyIR,
} from '../ir'
import { describeCardinality, formatValueType, isUnconstrained, typeParams } from '../ir'
import type { Capabilities, EmitOptions, EmitResult } from '../capabilities'

/**
 * The schema card: the whole model compressed for a prompt, one line per element.
 * A documentation target loses nothing — everything here is carried, so the full
 * capability set is declared and no downgrade is ever reported.
 * See lat.md/emitters#Context Target.
 */
export const CONTEXT_CAPABILITIES: Capabilities = {
  target: 'context',
  multiLabel: true,
  inheritance: 'subclass',
  requiredConstraint: 'enforced',
  uniqueConstraint: 'enforced',
  compositeKey: 'native',
  edgeProps: 'native',
  nestedEdges: false,
  listProps: 'native',
  compositeTypes: 'native',
  enums: 'documented',
  openTypes: 'native',
  valueConstraints: 'enforced',
  namedConstraints: 'enforced',
  rawPassthrough: true,
  cardinality: 'enforced',
}

/** One property, as `name: type` plus the marks the legend defines. */
function prop(p: PropertyIR): string {
  const type = p.composite ? formatValueType(p.composite)
    : `${p.type}${typeParams(p)}${p.list ? '[]' : ''}`
  const marks: string[] = []
  if (p.required) marks.push('!')
  if (p.unique) marks.push('^')
  const bounds: string[] = []
  if (p.min !== undefined || p.max !== undefined) bounds.push(`${p.min ?? ''}..${p.max ?? ''}`)
  if (p.minLength !== undefined || p.maxLength !== undefined) {
    bounds.push(`len ${p.minLength ?? ''}..${p.maxLength ?? ''}`)
  }
  if (p.pattern !== undefined) bounds.push(`/${p.pattern}/`)
  const enumRef = p.enum ? ` =${p.enum}` : ''
  return `${p.name}${marks.join('')}: ${type}${enumRef}${bounds.length > 0 ? ` [${bounds.join(', ')}]` : ''}`
}

/** An assertion in the words the inspector uses. */
function assertion(a: Assertion): string {
  switch (a.kind) {
    case 'lessThan': case 'lessThanOrEquals': case 'equals': case 'disjoint':
      return `${a.left} ${a.kind} ${a.right}`
    case 'atLeastOne': return `at least one of ${a.props.join(', ')}`
    case 'exactlyOne': return `exactly one of ${a.props.join(', ')}`
    case 'count': {
      const of = a.of ? ` of type ${a.of}` : ''
      const min = a.min !== undefined ? ` min ${a.min}` : ''
      const max = a.max !== undefined ? ` max ${a.max}` : ''
      return `count of ${a.edge}${of}:${min}${max}`
    }
  }
}

const constraintLine = (k: ConstraintIR): string =>
  `${k.name}: ${assertion(k.assert)}${k.severity && k.severity !== 'violation' ? ` (${k.severity})` : ''}`

function nodeLine(node: NodeTypeIR): string[] {
  const head: string[] = [`- **${node.name}**`]
  if (node.abstract) head.push('(abstract)')
  if (node.open) head.push('(open)')
  if (node.extends) head.push(`< ${node.extends}`)
  for (const m of node.mixins) head.push(`+${m}`)
  if (node.key.length > 0) {
    head.push(`key: ${node.key.join('+')}${node.keyInheritedFrom ? ` (from ${node.keyInheritedFrom})` : ''}`)
  }
  // Own properties only: the parent's and the mixin's lines already carry the rest.
  const own = node.props.filter((p) => !p.inheritedFrom)
  const lines = [`${head.join(' ')}${own.length > 0 ? ` — ${own.map(prop).join(', ')}` : ''}`]
  for (const k of node.constraints) lines.push(`  - constraint ${constraintLine(k)}`)
  if (node.rawShacl) {
    lines.push('  - raw SHACL:', ...node.rawShacl.trimEnd().split('\n').map((l) => `    ${l}`))
  }
  return lines
}

function edgeLine(edge: EdgeTypeIR): string {
  const card = isUnconstrained(edge.cardinality) ? '' : `, ${describeCardinality(edge.cardinality)}`
  const props = edge.props.length > 0 ? ` — ${edge.props.map(prop).join(', ')}` : ''
  return `- **${edge.name}**: ${edge.from} → ${edge.to}${card}${props}`
}

export function emitContext(model: ModelIR, _options: EmitOptions = {}): EmitResult {
  const parts: string[] = [
    `# Schema ${model.namespace.prefix} <${model.namespace.iri}>`,
    '',
    'Generated by lpg-modeler. Target: context. This card describes the schema for',
    'grounding queries and agents; it does not enforce anything itself.',
    'Legend: `!` required, `^` unique, `< Parent` supertype, `+Mixin` applied mixin,',
    '`=Enum` value set, `[a..b]` value bounds, `A → B` edge direction.',
    '',
  ]

  parts.push('## Node types')
  for (const node of model.nodes) parts.push(...nodeLine(node))

  if (model.edges.length > 0) {
    parts.push('', '## Edge types')
    for (const edge of model.edges) parts.push(edgeLine(edge))
  }

  if (model.mixins.length > 0) {
    parts.push('', '## Mixins')
    for (const m of model.mixins) {
      parts.push(`- **${m.name}** — ${m.props.map(prop).join(', ')}`)
    }
  }

  if (model.enums.length > 0) {
    parts.push('', '## Enums')
    for (const e of model.enums) parts.push(`- **${e.name}**: ${e.values.join(' | ')}`)
  }

  return { target: 'context', extension: 'md', content: parts.join('\n') + '\n', diagnostics: [] }
}
