import type { Diagnostic, ModelIR, PropertyIR } from '../ir'
import { findEnum } from '../ir'
import { downgrade, type Capabilities, type EmitOptions, type EmitResult } from '../capabilities'
import { LOSSY_TYPES, XSD, mapEdges, prefixHeader, term } from './reify'

/**
 * OWL is open-world inference, so only assertional constructs are emitted. Mapping an
 * LPG constraint into a domain, range, or cardinality restriction does not lose the
 * constraint, it inverts its meaning. See lat.md/emitters#OWL Subset.
 */
export const OWL_CAPABILITIES: Capabilities = {
  target: 'owl',
  multiLabel: true,
  inheritance: 'subclass',
  requiredConstraint: 'unsupported',
  uniqueConstraint: 'unsupported',
  compositeKey: 'native',
  edgeProps: 'reified',
  nestedEdges: false,
  listProps: 'native',
  enums: 'enforced',
  // OWL is open-world by construction, so closure is not something it can assert.
  openTypes: 'always-open',
  // Cardinality restrictions are deliberately omitted; see the safe assertional subset.
  cardinality: 'unsupported',
}

export function emitOwl(model: ModelIR, _options: EmitOptions = {}): EmitResult {
  const diagnostics: Diagnostic[] = []
  const parts: string[] = [
    '# Generated by lpg-modeler. Target: owl.',
    '#',
    '# Deliberately restricted to the safe assertional subset: classes, subClassOf and',
    '# hasKey. No rdfs:domain, no rdfs:range, and no cardinality restrictions are',
    '# emitted -- those state inference rules, not constraints, and a reasoner would',
    '# use them to classify individuals rather than to reject bad data. Constraints',
    '# are carried by the SHACL artifact. See lat.md/emitters#OWL Subset.',
    '',
    ...prefixHeader(model, [
      ['owl', 'http://www.w3.org/2002/07/owl#'],
      ['rdfs', 'http://www.w3.org/2000/01/rdf-schema#'],
      ['xsd', 'http://www.w3.org/2001/XMLSchema#'],
    ]),
    '',
  ]

  // --- Classes and the subclass backbone.
  for (const node of model.nodes) {
    const lines = [`${term(node)} a owl:Class ;`]
    lines.push(`  rdfs:label "${node.name}" ;`)
    if (node.extends) {
      const parent = model.nodes.find((n) => n.name === node.extends)
      if (parent) lines.push(`  rdfs:subClassOf ${term(parent)} ;`)
    }
    if (node.key.length > 0) {
      const keyTerms = node.key.map((k) => `${node.prefix}:${k}`).join(' ')
      lines.push(`  owl:hasKey ( ${keyTerms} ) ;`)
    }
    if (node.previousIri) {
      lines.push(`  owl:equivalentClass <${node.previousIri}> ;`)
    }
    if (node.abstract) {
      lines.unshift(`# '${node.name}' is abstract in the model. OWL has no notion of an`)
      lines.unshift('# uninstantiable class, so it is emitted as an ordinary class.')
    }
    const last = lines.length - 1
    lines[last] = (lines[last] ?? '').replace(/ ;$/, ' .')
    parts.push(...lines, '')
  }

  // --- Enumerated value sets, as OWL 2 datatype definitions. This is assertional and
  // stays inside OWL DL, so it is one of the few constraints safe to carry here.
  for (const e of model.enums) {
    const values = e.values.map((v) => `"${v}"`).join(' ')
    parts.push(
      `${e.prefix}:${e.name} a rdfs:Datatype ;`,
      `  owl:equivalentClass [ a rdfs:Datatype ; owl:oneOf ( ${values} ) ] .`)
  }
  if (model.enums.length > 0) parts.push('')

  /** The range of a property: its enum datatype when it has one, else the XSD type. */
  const rangeOf = (p: PropertyIR): string => {
    const e = p.enum ? findEnum(model, p.enum) : undefined
    return e ? `${e.prefix}:${e.name}` : XSD[p.type]
  }

  // --- Datatype properties, declared without domain or range.
  const declared = new Set<string>()
  for (const node of model.nodes) {
    for (const p of node.props) {
      const t = `${node.prefix}:${p.name}`
      if (declared.has(t)) continue
      declared.add(t)
      parts.push(`${t} a owl:DatatypeProperty ; rdfs:label "${p.name}" ; rdfs:range ${rangeOf(p)} .`)
      if (LOSSY_TYPES.has(p.type)) {
        downgrade(diagnostics, 'owl', 'downgrade-type',
          `Property '${node.name}.${p.name}' has type ${p.type}, which RDF has no dedicated datatype for. Declared as ${XSD[p.type]}.`,
          p.loc)
      }
      if (p.required) {
        downgrade(diagnostics, 'owl', 'downgrade-required',
          `Property '${node.name}.${p.name}' is required. OWL cannot express that as a constraint; the SHACL artifact carries it.`,
          p.loc)
      }
      if (p.unique) {
        downgrade(diagnostics, 'owl', 'downgrade-unique',
          `Property '${node.name}.${p.name}' is unique. OWL cannot express that as a constraint; the SHACL artifact carries it.`,
          p.loc)
      }
    }
  }
  parts.push('')

  // --- Edges, by gradual reification.
  for (const m of mapEdges(model)) {
    if (m.edge.cardinality !== 'many-to-many') {
      downgrade(diagnostics, 'owl', 'downgrade-cardinality',
        `Edge type '${m.edge.name}' declares ${m.edge.cardinality} cardinality. A cardinality restriction is deliberately not emitted here, because it would state an inference rule rather than a constraint; the SHACL artifact carries it.`,
        m.edge.loc)
    }
    if (m.kind === 'plain') {
      parts.push(
        `# (:${m.edge.from})-[:${m.edge.name}]->(:${m.edge.to}) carries no properties,`,
        '# so it stays a plain object property. No domain or range is asserted.',
        `${term(m.edge, m.property)} a owl:ObjectProperty ; rdfs:label "${m.edge.name}" .`,
        '')
      continue
    }
    parts.push(
      `# (:${m.edge.from})-[:${m.edge.name}]->(:${m.edge.to}) carries properties, so it is`,
      `# reified into a class. '${m.shortcutProperty}' is the shortcut for querying.`,
      `${term(m.edge, m.className)} a owl:Class ; rdfs:label "${m.edge.name}" .`,
      `${term(m.edge, m.subjectProperty)} a owl:ObjectProperty .`,
      `${term(m.edge, m.objectProperty)} a owl:ObjectProperty .`,
      `${term(m.edge, m.shortcutProperty)} a owl:ObjectProperty .`)
    for (const p of m.edge.props) {
      parts.push(`${m.edge.prefix}:${p.name} a owl:DatatypeProperty ; rdfs:range ${rangeOf(p)} .`)
    }
    if (m.edge.previousIri) {
      parts.push(`${term(m.edge, m.className)} owl:equivalentClass <${m.edge.previousIri}> .`)
    }
    parts.push('')
  }

  return { target: 'owl', extension: 'ttl', content: parts.join('\n'), diagnostics }
}
