import type { Diagnostic, ModelIR, NodeTypeIR, PropertyIR } from '../ir'
import { concreteNodes } from '../ir'
import { downgrade, type Capabilities, type EmitOptions, type EmitResult } from '../capabilities'
import { LOSSY_TYPES, XSD, mapEdges, prefixHeader, term } from './reify'

/**
 * SHACL is closed-world validation, so it means what an LPG schema means: a shape
 * genuinely rejects data that violates the model. See lat.md/emitters#SHACL Shapes.
 */
export const SHACL_CAPABILITIES: Capabilities = {
  target: 'shacl',
  multiLabel: true,
  inheritance: 'subclass',
  requiredConstraint: 'enforced',
  uniqueConstraint: 'unsupported',
  compositeKey: 'native',
  edgeProps: 'reified',
  nestedEdges: false,
}

function propertyShape(
  prefix: string, owner: string, p: PropertyIR, isKey: boolean, diags: Diagnostic[],
): string[] {
  const lines = [
    '  sh:property [',
    `    sh:path ${prefix}:${p.name} ;`,
    `    sh:datatype ${XSD[p.type]} ;`,
    '    sh:maxCount 1 ;',
  ]
  if (p.required || isKey) lines.push('    sh:minCount 1 ;')
  if (LOSSY_TYPES.has(p.type)) {
    downgrade(diags, 'shacl', 'downgrade-type',
      `Property '${owner}.${p.name}' has type ${p.type}, which RDF has no dedicated datatype for. Constrained as ${XSD[p.type]}.`,
      p.loc)
    lines.push(`    # DOWNGRADE: model type '${p.type}' has no RDF datatype; using ${XSD[p.type]}.`)
  }
  if (p.unique && !isKey) {
    downgrade(diags, 'shacl', 'downgrade-unique',
      `Property '${owner}.${p.name}' is unique, which core SHACL cannot express: uniqueness across all instances needs a SPARQL-based constraint.`,
      p.loc)
    lines.push(`    # UNENFORCED: '${p.name}' is unique in the model; core SHACL cannot express`)
    lines.push(`    # uniqueness across instances without a SPARQL constraint.`)
  }
  lines.push('  ] ;')
  return lines
}

function nodeShape(node: NodeTypeIR, diags: Diagnostic[]): string[] {
  const shape = `${term(node)}Shape`
  const lines = [`${shape} a sh:NodeShape ;`, `  sh:targetClass ${term(node)} ;`]
  for (const p of node.props) {
    lines.push(...propertyShape(node.prefix, node.name, p, node.key.includes(p.name), diags))
  }
  const last = lines.length - 1
  lines[last] = (lines[last] ?? '').replace(/ ;$/, ' .')
  return lines
}

export function emitShacl(model: ModelIR, _options: EmitOptions = {}): EmitResult {
  const diagnostics: Diagnostic[] = []
  const parts: string[] = [
    '# Generated by lpg-modeler. Target: shacl.',
    '#',
    '# SHACL carries the constraints because it is closed-world, and so means what the',
    '# model means. The ontology alongside it asserts only what is safe to assert.',
    '# See lat.md/emitters#SHACL Shapes.',
    '',
    ...prefixHeader(model, [
      ['sh', 'http://www.w3.org/ns/shacl#'],
      ['xsd', 'http://www.w3.org/2001/XMLSchema#'],
    ]),
    '',
  ]

  for (const node of concreteNodes(model)) {
    parts.push(...nodeShape(node, diagnostics), '')
  }

  // An edge carrying properties is reified into a class, so its properties get a shape.
  for (const m of mapEdges(model)) {
    if (m.kind !== 'reified') continue
    const shape = `${term(m.edge, m.className)}Shape`
    const lines = [
      `# Reified from (:${m.edge.from})-[:${m.edge.name}]->(:${m.edge.to})`,
      `${shape} a sh:NodeShape ;`,
      `  sh:targetClass ${term(m.edge, m.className)} ;`,
      '  sh:property [',
      `    sh:path ${term(m.edge, m.subjectProperty)} ;`,
      '    sh:minCount 1 ; sh:maxCount 1 ;',
      '  ] ;',
      '  sh:property [',
      `    sh:path ${term(m.edge, m.objectProperty)} ;`,
      '    sh:minCount 1 ; sh:maxCount 1 ;',
      '  ] ;',
    ]
    for (const p of m.edge.props) {
      lines.push(...propertyShape(m.edge.prefix, m.edge.name, p, false, diagnostics))
    }
    const last = lines.length - 1
    lines[last] = (lines[last] ?? '').replace(/ ;$/, ' .')
    parts.push(...lines, '')
  }

  return { target: 'shacl', extension: 'ttl', content: parts.join('\n'), diagnostics }
}
