// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   breaking  property Car.rating: added as int, required

CREATE CONSTRAINT ON (n:Car) ASSERT EXISTS (n.rating);
CREATE CONSTRAINT ON (n:Car) ASSERT n.rating IS TYPED INTEGER;
CREATE INDEX ON :Car(rating);
