// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   breaking  property Car.rating: added as int, required

CREATE CONSTRAINT car_rating_exists IF NOT EXISTS
  FOR (n:Car) REQUIRE n.rating IS NOT NULL;
CREATE INDEX car_rating IF NOT EXISTS
  FOR (n:Car) ON (n.rating);
