// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   breaking  property Car.rating: added as int, required

// UNENFORCED: 'rating' is required in the model; LadybugDB has no NOT NULL.
ALTER TABLE Car ADD rating INT64;
