// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   additive  node Trust: added

CREATE CONSTRAINT ON (n:Trust) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Trust) ASSERT EXISTS (n.id);
CREATE INDEX ON :Trust(id);
CREATE CONSTRAINT ON (n:Trust) ASSERT n.id IS TYPED STRING;
