#!/bin/sh
# Generated by lpg-modeler. Target: falkordb migration.
# Model: shop <https://example.org/shop#>
# Revision 3 -> 4.
#
# sh <this file>            REDIS_CLI and GRAPH_KEY override the defaults below.
#
# Not idempotent: FalkorDB has no IF EXISTS for dropping an index or a constraint, so
# run it once, against a graph at the previous revision. A constraint is applied
# asynchronously; check CALL db.constraints() afterwards rather than assuming.
#
# Changes since revision 3:
#   additive  property Party.phone: added as string

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-shop}"

# No schema effect on falkordb: nothing this target stores differs between the two revisions.
