// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   breaking  property Person.nickname: became unique

CREATE CONSTRAINT person_nickname_unique IF NOT EXISTS
  FOR (n:Person) REQUIRE n.nickname IS UNIQUE;
