// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: community.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   additive  node Trust: added

// DOWNGRADE: NODE KEY requires Enterprise. Uniqueness only; presence unenforced.
CREATE CONSTRAINT trust_key_unique IF NOT EXISTS
  FOR (n:Trust) REQUIRE (n.id) IS UNIQUE;
