// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   additive  node Bike: added
//   additive  property Bike.serial: added as string, required

CREATE NODE TABLE IF NOT EXISTS Bike (
  serial STRING,
  PRIMARY KEY(serial)
);
