// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   additive  node Bike: added
//   additive  property Bike.serial: added as string, required

CREATE CONSTRAINT ON (n:Bike) ASSERT n.serial IS UNIQUE;
CREATE CONSTRAINT ON (n:Bike) ASSERT EXISTS (n.serial);
CREATE INDEX ON :Bike(serial);
CREATE CONSTRAINT ON (n:Bike) ASSERT n.serial IS TYPED STRING;
