// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   additive  edge OWNS: cardinality changed from one-to-many to many-to-many

// DESTRUCTIVE: edge OWNS: recreated, discarding its relationships
DROP TABLE OWNS;

CREATE REL TABLE IF NOT EXISTS OWNS (
  // 'Party' and/or 'Car' are abstract; expanded to 2 endpoint pairs.
  FROM Company TO Car,
  FROM Person TO Car,
  since DATE
);
