// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   breaking  node Car: key changed from (vin) to (vin, seats)

// DESTRUCTIVE: edge OWNS: recreated, discarding its relationships
DROP TABLE OWNS;

// DOWNGRADE: LadybugDB cannot change a primary key in place.
// DESTRUCTIVE: node Car: recreated to change its primary key, discarding its rows
DROP TABLE Car;

CREATE NODE TABLE IF NOT EXISTS Car (
  // UNENFORCED: 'vin' is required in the model; LadybugDB has no NOT NULL.
  vin STRING,
  seats INT64,
  // UNENFORCED: 'status' is limited to enum 'Status' in the model.
  status STRING,
  // SYNTHESIZED: composite key (vin, seats) is not expressible;
  // 'car_key' must be written as the concatenation of those properties.
  car_key STRING,
  PRIMARY KEY(car_key)
);

CREATE REL TABLE IF NOT EXISTS OWNS (
  // 'Party' and/or 'Car' are abstract; expanded to 2 endpoint pairs.
  FROM Company TO Car,
  FROM Person TO Car,
  since DATE,
  // one-to-many: enforced on write.
  ONE_MANY
);
