// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   breaking  node Car: key changed from (vin) to (vin, seats)

DROP CONSTRAINT ON (n:Car) ASSERT n.vin IS UNIQUE;
DROP INDEX ON :Car(vin);

CREATE CONSTRAINT ON (n:Car) ASSERT n.vin, n.seats IS UNIQUE;
CREATE CONSTRAINT ON (n:Car) ASSERT EXISTS (n.seats);
CREATE INDEX ON :Car(vin, seats);
