// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   additive  property Person.email: no longer unique

DROP CONSTRAINT person_email_unique IF EXISTS;

