// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   destructive  node Car: removed
//   destructive  property Car.seats: removed
//   destructive  property Car.status: removed
//   destructive  property Car.vin: removed
//   destructive  property OWNS.since: removed
//   destructive  edge OWNS: removed

// DESTRUCTIVE: Car: constraint car_key dropped with the type
DROP CONSTRAINT car_key IF EXISTS;

// DESTRUCTIVE: edge OWNS: deleted with its type
MATCH ()-[r:OWNS]->() CALL { WITH r DELETE r } IN TRANSACTIONS;
// DESTRUCTIVE: node Car: deleted with its type
MATCH (n:Car) CALL { WITH n DETACH DELETE n } IN TRANSACTIONS;

