#!/bin/sh
# Generated by lpg-modeler. Target: falkordb migration.
# Model: shop <https://example.org/shop#>
# Revision 3 -> 4.
#
# sh <this file>            REDIS_CLI and GRAPH_KEY override the defaults below.
#
# Not idempotent: FalkorDB has no IF EXISTS for dropping an index or a constraint, so
# run it once, against a graph at the previous revision. A constraint is applied
# asynchronously; check CALL db.constraints() afterwards rather than assuming.
#
# Changes since revision 3:
#   destructive  node Car: removed
#   destructive  property Car.seats: removed
#   destructive  property Car.status: removed
#   destructive  property Car.vin: removed
#   destructive  property OWNS.since: removed
#   destructive  edge OWNS: removed

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-shop}"

# DESTRUCTIVE: Car: UNIQUE constraint dropped with the type
$REDIS_CLI GRAPH.CONSTRAINT DROP "$GRAPH_KEY" UNIQUE NODE Car PROPERTIES 1 vin
# DESTRUCTIVE: Car: MANDATORY constraint dropped with the type
$REDIS_CLI GRAPH.CONSTRAINT DROP "$GRAPH_KEY" MANDATORY NODE Car PROPERTIES 1 vin
# DESTRUCTIVE: Car: index dropped with the type
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "DROP INDEX FOR (n:Car) ON (n.vin)"

# DESTRUCTIVE: edge OWNS: deleted with its type
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "MATCH ()-[r:OWNS]->() DELETE r"
# DESTRUCTIVE: node Car: deleted with its type
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "MATCH (n:Car) DETACH DELETE n"

