// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   destructive  node Car: removed
//   destructive  property Car.seats: removed
//   destructive  property Car.status: removed
//   destructive  property Car.vin: removed
//   destructive  property OWNS.since: removed
//   destructive  edge OWNS: removed

// DESTRUCTIVE: edge OWNS: removed, discarding its relationships
DROP TABLE OWNS;

// DESTRUCTIVE: node Car: removed, discarding its rows
DROP TABLE Car;
