// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   destructive  node Car: removed
//   destructive  property Car.seats: removed
//   destructive  property Car.status: removed
//   destructive  property Car.vin: removed
//   destructive  property OWNS.since: removed
//   destructive  edge OWNS: removed

// DESTRUCTIVE: Car: constraint dropped with the type
DROP CONSTRAINT ON (n:Car) ASSERT n.vin IS UNIQUE;
// DESTRUCTIVE: Car: constraint dropped with the type
DROP CONSTRAINT ON (n:Car) ASSERT EXISTS (n.vin);
// DESTRUCTIVE: Car: constraint dropped with the type
DROP CONSTRAINT ON (n:Car) ASSERT n.vin IS TYPED STRING;
// DESTRUCTIVE: Car: constraint dropped with the type
DROP CONSTRAINT ON (n:Car) ASSERT n.seats IS TYPED INTEGER;
// DESTRUCTIVE: Car: constraint dropped with the type
DROP CONSTRAINT ON (n:Car) ASSERT n.status IS TYPED ENUM;
// DESTRUCTIVE: Car: index dropped with the type
DROP INDEX ON :Car(vin);

// DESTRUCTIVE: edge OWNS: deleted with its type
USING PERIODIC COMMIT 1000 MATCH ()-[r:OWNS]->() DELETE r;
// DESTRUCTIVE: node Car: deleted with its type
USING PERIODIC COMMIT 1000 MATCH (n:Car) DETACH DELETE n;

