// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   breaking  node Individual: renamed from 'Person'

DROP CONSTRAINT person_key IF EXISTS;
DROP CONSTRAINT person_email_unique IF EXISTS;

MATCH (n:Person) CALL { WITH n SET n:Individual REMOVE n:Person } IN TRANSACTIONS;

CREATE CONSTRAINT individual_key IF NOT EXISTS
  FOR (n:Individual) REQUIRE (n.id) IS NODE KEY;
CREATE CONSTRAINT individual_email_unique IF NOT EXISTS
  FOR (n:Individual) REQUIRE n.email IS UNIQUE;
