// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   breaking  property Person.mail: renamed from 'email'

DROP CONSTRAINT ON (n:Person) ASSERT n.email IS UNIQUE;
DROP CONSTRAINT ON (n:Person) ASSERT n.email IS TYPED STRING;

USING PERIODIC COMMIT 1000 MATCH (n:Person) WHERE n.email IS NOT NULL SET n.mail = n.email REMOVE n.email;

CREATE CONSTRAINT ON (n:Person) ASSERT n.mail IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT n.mail IS TYPED STRING;
