// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: community.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   breaking  edge ACQUAINTED: renamed from 'KNOWS'

MATCH (a)-[r:KNOWS]->(b) CALL { WITH a, r, b CREATE (a)-[r2:ACQUAINTED]->(b) SET r2 = properties(r) DELETE r } IN TRANSACTIONS;

