// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   breaking  edge ACQUAINTED: renamed from 'KNOWS'

USING PERIODIC COMMIT 1000 MATCH (a)-[r:KNOWS]->(b) CREATE (a)-[r2:ACQUAINTED]->(b) SET r2 = properties(r) DELETE r;

