// Generated by lpg-modeler. Target: memgraph migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to an instance at the previous revision, e.g. with `lpg apply`.
// Data steps use USING PERIODIC COMMIT, which runs only in an implicit (auto-commit)
// transaction. Measured against Memgraph 3.13.1 Community.
//
// Changes since revision 3:
//   breaking  node Individual: renamed from 'Person'

DROP CONSTRAINT ON (n:Person) ASSERT n.id IS UNIQUE;
DROP CONSTRAINT ON (n:Person) ASSERT EXISTS (n.id);
DROP CONSTRAINT ON (n:Person) ASSERT n.email IS UNIQUE;
DROP CONSTRAINT ON (n:Person) ASSERT n.email IS TYPED STRING;
DROP CONSTRAINT ON (n:Person) ASSERT n.nickname IS TYPED STRING;
DROP CONSTRAINT ON (n:Person) ASSERT n.createdAt IS TYPED LOCALDATETIME;
DROP CONSTRAINT ON (n:Person) ASSERT n.id IS TYPED STRING;
DROP INDEX ON :Person(id);

USING PERIODIC COMMIT 1000 MATCH (n:Person) SET n:Individual REMOVE n:Person;

CREATE CONSTRAINT ON (n:Individual) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Individual) ASSERT EXISTS (n.id);
CREATE INDEX ON :Individual(id);
CREATE CONSTRAINT ON (n:Individual) ASSERT n.email IS UNIQUE;
CREATE CONSTRAINT ON (n:Individual) ASSERT n.email IS TYPED STRING;
CREATE CONSTRAINT ON (n:Individual) ASSERT n.nickname IS TYPED STRING;
CREATE CONSTRAINT ON (n:Individual) ASSERT n.createdAt IS TYPED LOCALDATETIME;
CREATE CONSTRAINT ON (n:Individual) ASSERT n.id IS TYPED STRING;
