#!/bin/sh
# Generated by lpg-modeler. Target: falkordb migration.
# Model: shop <https://example.org/shop#>
# Revision 3 -> 4.
#
# sh <this file>            REDIS_CLI and GRAPH_KEY override the defaults below.
#
# Not idempotent: FalkorDB has no IF EXISTS for dropping an index or a constraint, so
# run it once, against a graph at the previous revision. A constraint is applied
# asynchronously; check CALL db.constraints() afterwards rather than assuming.
#
# Changes since revision 3:
#   breaking  edge ACQUAINTED: renamed from 'KNOWS'

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-shop}"

$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "MATCH (a)-[r:KNOWS]->(b) CREATE (a)-[r2:ACQUAINTED]->(b) SET r2 = properties(r) DELETE r"

