// Generated by lpg-modeler. Target: neo4j migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Edition: enterprise.
// Data steps use CALL { ... } IN TRANSACTIONS, which runs only in an implicit
// (auto-commit) transaction: in cypher-shell run the file as is; in Browser prefix :auto.
// Relabelling a large graph is slow and is batched for that reason.
//
// Changes since revision 3:
//   breaking  property Person.mail: renamed from 'email'

DROP CONSTRAINT person_email_unique IF EXISTS;

MATCH (n:Person) WHERE n.email IS NOT NULL CALL { WITH n SET n.mail = n.email REMOVE n.email } IN TRANSACTIONS;

CREATE CONSTRAINT person_mail_unique IF NOT EXISTS
  FOR (n:Person) REQUIRE n.mail IS UNIQUE;
