// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   breaking  node Individual: renamed from 'Person'

ALTER TABLE Person RENAME TO Individual;
