#!/bin/sh
# Generated by lpg-modeler. Target: falkordb migration.
# Model: shop <https://example.org/shop#>
# Revision 3 -> 4.
#
# sh <this file>            REDIS_CLI and GRAPH_KEY override the defaults below.
#
# Not idempotent: FalkorDB has no IF EXISTS for dropping an index or a constraint, so
# run it once, against a graph at the previous revision. A constraint is applied
# asynchronously; check CALL db.constraints() afterwards rather than assuming.
#
# Changes since revision 3:
#   breaking  node Individual: renamed from 'Person'

REDIS_CLI="${REDIS_CLI:-redis-cli}"
GRAPH_KEY="${GRAPH_KEY:-shop}"

$REDIS_CLI GRAPH.CONSTRAINT DROP "$GRAPH_KEY" UNIQUE NODE Person PROPERTIES 1 id
$REDIS_CLI GRAPH.CONSTRAINT DROP "$GRAPH_KEY" MANDATORY NODE Person PROPERTIES 1 id
$REDIS_CLI GRAPH.CONSTRAINT DROP "$GRAPH_KEY" UNIQUE NODE Person PROPERTIES 1 email
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "DROP INDEX FOR (n:Person) ON (n.id)"
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "DROP INDEX FOR (n:Person) ON (n.email)"

$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "MATCH (n:Person) SET n:Individual REMOVE n:Person"

$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Individual) ON (n.id)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Individual PROPERTIES 1 id
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" MANDATORY NODE Individual PROPERTIES 1 id
$REDIS_CLI GRAPH.QUERY "$GRAPH_KEY" "CREATE INDEX FOR (n:Individual) ON (n.email)"
$REDIS_CLI GRAPH.CONSTRAINT CREATE "$GRAPH_KEY" UNIQUE NODE Individual PROPERTIES 1 email
