// Generated by lpg-modeler. Target: ladybug migration.
// Model: shop <https://example.org/shop#>
// Revision 3 -> 4.
//
// Apply once, to a database built from the previous revision's DDL. The statements run
// in order with no enclosing transaction, so take a backup first.
//
// Changes since revision 3:
//   breaking  property Car.seats: type changed from int to string

// DOWNGRADE: LadybugDB cannot change a column type in place.
// DESTRUCTIVE: property Car.seats: retyped from INT64, discarding its values
ALTER TABLE Car DROP seats;
ALTER TABLE Car ADD seats STRING;
