// Generated by lpg-modeler. Target: memgraph.
// Model: bk <https://example.org/vocab/booking#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

CREATE ENUM Status VALUES { held, confirmed, cancelled };

// Booking
CREATE CONSTRAINT ON (n:Booking) ASSERT n.ref IS UNIQUE;
CREATE CONSTRAINT ON (n:Booking) ASSERT EXISTS (n.ref);
CREATE INDEX ON :Booking(ref);
CREATE CONSTRAINT ON (n:Booking) ASSERT n.ref IS TYPED STRING;
// PARTIAL: 'status' must be an enum value; that it is a Status value is unenforced.
CREATE CONSTRAINT ON (n:Booking) ASSERT n.status IS TYPED ENUM;
CREATE CONSTRAINT ON (n:Booking) ASSERT EXISTS (n.startDate);
CREATE CONSTRAINT ON (n:Booking) ASSERT n.startDate IS TYPED DATE;
CREATE CONSTRAINT ON (n:Booking) ASSERT EXISTS (n.endDate);
CREATE CONSTRAINT ON (n:Booking) ASSERT n.endDate IS TYPED DATE;
CREATE CONSTRAINT ON (n:Booking) ASSERT n.nights IS TYPED INTEGER;
CREATE INDEX ON :Booking(startDate);
CREATE INDEX ON :Booking(endDate);

// Guest
CREATE CONSTRAINT ON (n:Guest) ASSERT n.email IS UNIQUE;
CREATE CONSTRAINT ON (n:Guest) ASSERT EXISTS (n.email);
CREATE INDEX ON :Guest(email);
CREATE CONSTRAINT ON (n:Guest) ASSERT n.email IS TYPED STRING;
CREATE CONSTRAINT ON (n:Guest) ASSERT n.phone IS TYPED STRING;
CREATE CONSTRAINT ON (n:Guest) ASSERT n.age IS TYPED INTEGER;

// (:Booking)-[:BOOKED_BY]->(:Guest)
// UNENFORCED: *-to-1..* in the model; Memgraph has no multiplicity constraint.
