// Generated by lpg-modeler. Target: memgraph.
// Model: cat <https://example.org/vocab/catalog#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

CREATE ENUM Format VALUES { vinyl, cd, digital };

// Artist
CREATE CONSTRAINT ON (n:Artist) ASSERT n.slug IS UNIQUE;
CREATE CONSTRAINT ON (n:Artist) ASSERT EXISTS (n.slug);
CREATE INDEX ON :Artist(slug);
CREATE CONSTRAINT ON (n:Artist) ASSERT n.slug IS TYPED STRING;
// PARTIAL: 'aliases' must be a list; its elements being string is unenforced.
CREATE CONSTRAINT ON (n:Artist) ASSERT n.aliases IS TYPED LIST;

// Release
CREATE CONSTRAINT ON (n:Release) ASSERT n.label, n.catalogNumber IS UNIQUE;
CREATE CONSTRAINT ON (n:Release) ASSERT EXISTS (n.label);
CREATE CONSTRAINT ON (n:Release) ASSERT EXISTS (n.catalogNumber);
CREATE INDEX ON :Release(label, catalogNumber);
CREATE CONSTRAINT ON (n:Release) ASSERT n.label IS TYPED STRING;
CREATE CONSTRAINT ON (n:Release) ASSERT n.catalogNumber IS TYPED STRING;
// PARTIAL: 'format' must be an enum value; that it is a Format value is unenforced.
CREATE CONSTRAINT ON (n:Release) ASSERT n.format IS TYPED ENUM;
// PARTIAL: 'genres' must be a list; its elements being string is unenforced.
CREATE CONSTRAINT ON (n:Release) ASSERT n.genres IS TYPED LIST;
CREATE CONSTRAINT ON (n:Release) ASSERT n.pressed IS TYPED DATE;
CREATE CONSTRAINT ON (n:Release) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Release) ASSERT n.createdAt IS TYPED ZONEDDATETIME;
CREATE INDEX ON :Release(createdAt);

// (:Release)-[:RELEASED_BY]->(:Artist)
// UNENFORCED: *-to-1..* in the model; Memgraph has no multiplicity constraint.
