// Generated by lpg-modeler. Target: memgraph.
// Model: fleet <https://example.org/vocab/fleet#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

CREATE ENUM Fuel VALUES { diesel, electric, hydrogen };

// Depot
CREATE CONSTRAINT ON (n:Depot) ASSERT n.code IS UNIQUE;
CREATE CONSTRAINT ON (n:Depot) ASSERT EXISTS (n.code);
CREATE INDEX ON :Depot(code);
CREATE CONSTRAINT ON (n:Depot) ASSERT n.code IS TYPED STRING;
CREATE CONSTRAINT ON (n:Depot) ASSERT n.name IS TYPED STRING;
CREATE CONSTRAINT ON (n:Depot) ASSERT n.latitude IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Depot) ASSERT n.longitude IS TYPED FLOAT;

// Driver
CREATE CONSTRAINT ON (n:Driver) ASSERT n.licence IS UNIQUE;
CREATE CONSTRAINT ON (n:Driver) ASSERT EXISTS (n.licence);
CREATE INDEX ON :Driver(licence);
CREATE CONSTRAINT ON (n:Driver) ASSERT n.licence IS TYPED STRING;
CREATE CONSTRAINT ON (n:Driver) ASSERT EXISTS (n.name);
CREATE CONSTRAINT ON (n:Driver) ASSERT n.name IS TYPED STRING;
CREATE CONSTRAINT ON (n:Driver) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Driver) ASSERT n.createdAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Driver) ASSERT n.updatedAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Driver) ASSERT EXISTS (n.createdBy);
CREATE CONSTRAINT ON (n:Driver) ASSERT n.createdBy IS TYPED STRING;
CREATE INDEX ON :Driver(name);
CREATE INDEX ON :Driver(createdAt);
CREATE INDEX ON :Driver(createdBy);

// Trailer carries labels :Trailer :Asset.
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.assetTag IS UNIQUE;
CREATE CONSTRAINT ON (n:Trailer) ASSERT EXISTS (n.assetTag);
CREATE INDEX ON :Trailer(assetTag);
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.lengthM IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Trailer) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.createdAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.updatedAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Trailer) ASSERT EXISTS (n.createdBy);
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.createdBy IS TYPED STRING;
CREATE CONSTRAINT ON (n:Trailer) ASSERT n.assetTag IS TYPED STRING;
CREATE INDEX ON :Trailer(createdAt);
CREATE INDEX ON :Trailer(createdBy);

// Truck carries labels :Truck :Vehicle :Asset.
CREATE CONSTRAINT ON (n:Truck) ASSERT n.assetTag IS UNIQUE;
CREATE CONSTRAINT ON (n:Truck) ASSERT EXISTS (n.assetTag);
CREATE INDEX ON :Truck(assetTag);
CREATE CONSTRAINT ON (n:Truck) ASSERT n.axles IS TYPED INTEGER;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.maxLoadKg IS TYPED INTEGER;
CREATE CONSTRAINT ON (n:Truck) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Truck) ASSERT n.createdAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.updatedAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.latitude IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.longitude IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.vin IS UNIQUE;
CREATE CONSTRAINT ON (n:Truck) ASSERT EXISTS (n.vin);
CREATE CONSTRAINT ON (n:Truck) ASSERT n.vin IS TYPED STRING;
// PARTIAL: 'fuel' must be an enum value; that it is a Fuel value is unenforced.
CREATE CONSTRAINT ON (n:Truck) ASSERT n.fuel IS TYPED ENUM;
CREATE CONSTRAINT ON (n:Truck) ASSERT n.assetTag IS TYPED STRING;
CREATE INDEX ON :Truck(createdAt);

// Van carries labels :Van :Vehicle :Asset.
CREATE CONSTRAINT ON (n:Van) ASSERT n.assetTag IS UNIQUE;
CREATE CONSTRAINT ON (n:Van) ASSERT EXISTS (n.assetTag);
CREATE INDEX ON :Van(assetTag);
CREATE CONSTRAINT ON (n:Van) ASSERT n.cargoVolumeM3 IS TYPED FLOAT;
CREATE CONSTRAINT ON (n:Van) ASSERT EXISTS (n.createdAt);
CREATE CONSTRAINT ON (n:Van) ASSERT n.createdAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Van) ASSERT n.updatedAt IS TYPED ZONEDDATETIME;
CREATE CONSTRAINT ON (n:Van) ASSERT n.vin IS UNIQUE;
CREATE CONSTRAINT ON (n:Van) ASSERT EXISTS (n.vin);
CREATE CONSTRAINT ON (n:Van) ASSERT n.vin IS TYPED STRING;
// PARTIAL: 'fuel' must be an enum value; that it is a Fuel value is unenforced.
CREATE CONSTRAINT ON (n:Van) ASSERT n.fuel IS TYPED ENUM;
CREATE CONSTRAINT ON (n:Van) ASSERT n.assetTag IS TYPED STRING;
CREATE INDEX ON :Van(createdAt);

// (:Driver)-[:DRIVES]->(:Vehicle)

// (:Asset)-[:STATIONED_AT]->(:Depot)
// UNENFORCED: many-to-one in the model; Memgraph has no multiplicity constraint.

// (:Truck)-[:TOWS]->(:Trailer)
// UNENFORCED: many-to-one in the model; Memgraph has no multiplicity constraint.
