// Generated by lpg-modeler. Target: memgraph.
// Model: kin <https://example.org/vocab/kin#>
//
// Measured against Memgraph 3.13.1 Community. See lat.md/emitters#Memgraph Target.
//
// Apply to a fresh instance, then carry it forward with `lpg migrate`: a type
// constraint and an enum cannot be created twice, and an enum outlives every reset.
//
// Enums are native here. A value is written as Enum::value, e.g. Status::active,
// and a plain string is rejected wherever a property is limited to an enum.
//
// A hierarchy is expressed as labels, so a node carries its own label and every
// ancestor label. Memgraph is schema-optional: a closed type is documentation here.

// Passport
CREATE CONSTRAINT ON (n:Passport) ASSERT n.number IS UNIQUE;
CREATE CONSTRAINT ON (n:Passport) ASSERT EXISTS (n.number);
CREATE INDEX ON :Passport(number);
CREATE CONSTRAINT ON (n:Passport) ASSERT n.number IS TYPED STRING;

// Person
CREATE CONSTRAINT ON (n:Person) ASSERT n.ssn IS UNIQUE;
CREATE CONSTRAINT ON (n:Person) ASSERT EXISTS (n.ssn);
CREATE INDEX ON :Person(ssn);
CREATE CONSTRAINT ON (n:Person) ASSERT n.ssn IS TYPED STRING;
CREATE CONSTRAINT ON (n:Person) ASSERT n.born IS TYPED DATE;

// (:Person)-[:HAS_PARENT]->(:Person)
// UNENFORCED: *-to-2 in the model; Memgraph has no multiplicity constraint.

// (:Passport)-[:HELD_BY]->(:Person)
// UNENFORCED: 0..1-to-1..* in the model; Memgraph has no multiplicity constraint.
